<?php
$num = $row["num"] ?? '';
$e_num = $row["num"] ?? 0 ; // int(11) // 반드시 num으로 _row.php에서는 받아와야 한다.
$is_deleted = $row["is_deleted"] ?? NULL;
$e_viewexcept_id = $row["e_viewexcept_id"] ?? ''; // text
$eworks_item = $row["eworks_item"] ?? ''; // text
$e_title = $row["e_title"] ?? ''; // text
$contents = $row["contents"] ?? ''; // text
$registdate = $row["registdate"] ?? ''; // datetime
$status = $row["status"] ?? ''; // text
$e_line = $row["e_line"] ?? ''; // text
$e_line_id = $row["e_line_id"] ?? ''; // text
$e_confirm = $row["e_confirm"] ?? ''; // text
$e_confirm_id = $row["e_confirm_id"] ?? ''; // text
$r_line = $row["r_line"] ?? ''; // text
$r_line_id = $row["r_line_id"] ?? ''; // text
$recordtime = $row["recordtime"] ?? ''; // datetime
$author = $row["author"] ?? ''; // text
$author_id = $row["author_id"] ?? ''; // text
$done = $row["done"] ?? ''; // text
$al_askdatefrom = $row["al_askdatefrom"] ?? ''; // date
$al_askdateto = $row["al_askdateto"] ?? ''; // date
$al_item = $row["al_item"] ?? ''; // text
$al_part = $row["al_part"] ?? ''; // text
$al_usedday = $row["al_usedday"] ?? ''; // text
$al_content = $row["al_content"] ?? ''; // text
$which = $row["which"] ?? ''; // text
$outdate = $row["outdate"] ?? ''; // date
$requestdate = $row["requestdate"] ?? ''; // date
$indate = $row["indate"] ?? ''; // date
$outworkplace = $row["outworkplace"] ?? ''; // text
$steel_item = $row["steel_item"] ?? ''; // text
$spec = $row["spec"] ?? ''; // text
$steelnum = $row["steelnum"] ?? ''; // text
$company = $row["company"] ?? ''; // text
$request_comment = $row["request_comment"] ?? ''; // text
$model = $row["model"] ?? ''; // text
$first_writer = $row["first_writer"] ?? ''; // text
$update_log = $row["update_log"] ?? ''; // text
$supplier = $row["supplier"] ?? ''; // text
$suppliercost = $row["suppliercost"] ?? ''; // text
$inventory = $row["inventory"] ?? ''; // text
$payment = $row["payment"] ?? ''; // text
$store = $row["store"] ?? ''; // text
?>
