name: Deploy to 8440.co.kr via FTP
on:
  push:
    branches: ["main"]

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ftp-deploy
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 1

      # 배포 소스 확인 (www 폴더만 올림)
      - name: Verify deploy source (./www/)
        run: |
          test -d ./www || (echo "::error::www/ not found" && exit 1)
          find ./www -maxdepth 2 -type f | head -n 20

      # 비어있는 디렉터리도 유지
      - name: Create empty .gitkeep files for empty directories
        run: |
          find ./www -type d -empty -exec touch {}/.gitkeep \;

      # FTP 연결 정보 로그(민감정보는 출력하지 않음)
      - name: Verify FTP connection settings (safe log)
        run: |
          echo "Server: ${{ secrets.FTP_SERVER }}"
          echo "User:   ${{ secrets.FTP_USERNAME }}"
          echo "Port:   ${{ secrets.FTP_PORT || '21' }}"
          echo "Dir:    ${{ secrets.FTP_REMOTE_DIR }}"
          # 끝 슬래시 강제 확인
          if [ -n "${{ secrets.FTP_REMOTE_DIR }}" ] && [ "${{ secrets.FTP_REMOTE_DIR }}" != */ ]; then
            echo "::warning::FTP_REMOTE_DIR should end with a slash. e.g. /www/"
          fi

      # FTP 배포
      - name: Deploy (FTP)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server:     ${{ secrets.FTP_SERVER }}        # ex) 8440.co.kr
          username:   ${{ secrets.FTP_USERNAME }}      # ex) mirae8440
          password:   ${{ secrets.FTP_PASSWORD }}
          protocol:   ftp                              # ← FTP 사용 (Action 지원 프로토콜)
          port:       ${{ secrets.FTP_PORT || 21 }}    # ← 21 (Secret 없으면 21 기본)
          server-dir: ${{ secrets.FTP_REMOTE_DIR }}    # ex) /www/ (슬래시 필수)
          local-dir:  "./www/"
          log-level:  verbose
          dry-run:    false
          exclude: |
            **/.git/**
            **/.git*
            **/.github/**
            **/.vscode/**
            **/.idea/**
            **/.history/**
            **/.cache/**
            **/.cursor/**
            **/.claude/**
            **/node_modules/**
            **/*.md
            **/*.yml
            **/*.yaml
            **/*.lock
            **/.DS_Store
            **/Thumbs.db
            **/__MACOSX/**
            **/uploads/**
            **/storage/**
            **/lib/**
            **/dbeditor/**
            **/bseditor/**
            **/_dompdf/**
            **/.well-known/**
            **/0/**
            **/1/**
